### ISSUE TITLE
TypeError: 'Response' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by ubuntu748** [apetrynet/pyfilemail#7]
Not too sure if this project is still maintained but.
I noticed that it doesn’t always run as expected. It will return the error:

Traceback (most recent call last):
  File "/home/pi/.local/bin/pyfilemail", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python2.7/site-packages/pyfilemail/__main__.py", line 250, in main
    zip_=args.compress
  File "/home/pi/.local/lib/python2.7/site-packages/pyfilemail/transfer.py", line 109, in __init__
    self._initialize()
  File "/home/pi/.local/lib/python2.7/site-packages/pyfilemail/transfer.py", line 133, in _initialize
    hellraiser(res)
  File "/home/pi/.local/lib/python2.7/site-packages/pyfilemail/errors.py", line 72, in hellraiser
    errorcode = response_dict['errorcode']
TypeError: 'Response' object has no attribute '__getitem__'

I have a feeling that this is because “filemail” is only accepting 1 link per day. As it will error after a single go, but work again the next day.

Also – given a “Large” file (~8G), it errors with a python overflow error.
(Unable to give error message until tomorrow)

Possibly due to the “small” chunks it is being split into.

**Comment by apetrynet** [comment]
Hi @ubuntu748 
Thank you for the bug report! You're actually the first indication of anyone using this :)

I've run into the same issues as you actually.
The one with limited links per day comes down to a limitation in the free account. I don't remember how many a day you can do though.

The large file issue is also a known one. As you noticed I haven't worked on this for a while, but I started working on a fix some time back, but never got it working properly. It's actually disconnects that don't recover properly. 
I'll give it another go in the near future.

Thanks again for using this tool and filing the issues!

**Comment by ubuntu748** [comment]
Wow - Speedy response.
I seems that "filemail" now only allow 2 "free" transfers per day per IP - yet what 2 means is not defined. I tried a "small" upload ~800M and it worked until the last few bytes where it stalled. When I tried again, it errored (even as this was the first and only upload).

Whilst this was a good idea at the time, I honestly don't think it is worth your time developing it any further, considering the lack of users and "filemail" restricting the access.

Thanks again for your hard work.

**Comment by apetrynet** [comment]
Hi again!

I'm sorry pyfilemail doesn't help you the way it should. 
Out of curiosity, did you register for an API key? It's free and you can do it yourself [here.](https://www.filemail.com/apidoc/ApiKey.aspx) Perhaps that will let you do more transfers since you are logged as a person and not a bot?

I'll still look at fixing this issue, so you'll get updates on the progress through github. My main problem is that my internet connection at home is really bad (20/3Mbs) so debugging transfer of "huge" files is quite a pain ;P

**Comment by ubuntu748** [comment]
Yes, I tried with an API key but alas it was exactly the same.

**Comment by apetrynet** [comment]
OK, thanks for the reply.
I'll keep you posted.
